from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from . import views

# from django.contrib.auth import views

urlpatterns = [
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('regrdo/', views.regrdo, name='regrdo'),
    path('reginst', views.reginst, name='reginst'),
    path('reginst/personal', views.InstPersonalInfo, name='reginst.personal'),
    path('reginst/modalities', views.InstitutionModalities, name='reginst.modalities'),
    path('regrdo/personal', views.PersonalInfo, name='regrdo.personal'),
    path('regrdo/qualificationdetails', views.QualificationDetails, name='regrdo.qualificationdetails'),
    path('regrdo/workexp', views.WorkExp, name='regrdo.workexp'),
    path('regrdo/bankinginfo', views.BankingInfo, name='regrdo.bankinginfo'),
    path('regrdo/reportingarea', views.ReportingArea, name='regrdo.reportingarea'),
    path('regrdo/timeavailability', views.TimeAvailability, name='regrdo.timeavailability'),
    path('prordo', views.prordo, name='prordo'),
    path('proinst', views.proinst, name='proinst'),
    path('user-exists', views.userExists, name='userexists'),
    path('number-exists', views.numberExists, name='numberexists'),
    path('phone-exists', views.phoneExists, name='phoneexists'),
    path('patientdata', views.patientData, name='patientdata'),
    path('patientdetails', views.patientDetails, name='patientdetails'),
    path('audiopatientdata', views.audiopatientDetails, name='audiopatientdata'),
    path('optometrydata', views.optopatientDetails, name='optometrydata'),
    path('vitalpatientdata', views.vitalpatientDetails, name='vitalpatientdata'),
    path('uploadcsv', views.uploadcsv, name='uploadcsv'),
    path('uploadcsvforaudio', views.uploadcsvforaudio, name='uploadcsvforaudio'),
    path('uploadcsvforopto', views.uploadcsvforopto, name='uploadcsvforopto'),
    path('uploadcsvforvital', views.uploadcsvforvital, name='uploadcsvforvital'),
    path('serviceslist', views.PersonalInfo, name='serviceslist'),
    path('ecgallocation', views.ecgallocation, name='ecgallocation'),
    path('xrayallocation', views.xrayallocation, name='xrayallocation'),
    path('audiometry', views.audiometry, name='audiometry'),
    path('allocation', views.allocation, name='ecgcoordinator'),
    path('allocation1', views.allocation1, name='xraycoordinator'),
    path('allocate/', views.allocate, name='allocate'),
    path('allocate1/', views.allocate1, name='allocate1'),
    path('fetch_patient_data', views.fetch_patient_data, name='fetch_patient_data'),
    path('googledrive/', views.Google.as_view(), name='upload_csv'),
    path('upload_dicom/', views.upload_dicom, name='upload_dicom'),
    path('upload_dicom.html', views.upload_dicom, name='upload_dicom'),
    path('api/update_patient_done_status/<str:patient_id>/', views.update_patient_done_status, name='update_patient_done_status'),
    path('api/update_patient_done_status_xray/<str:patient_id>/', views.update_patient_done_status_xray, name='update_patient_done_status_xray'),
    path('api/reject_patient_status/<str:patient_id>/', views.reject_patient_status, name='reject_patient_status'),
    path('upload_ecg_pdf/', views.upload_ecg_pdf, name='upload_ecg_pdf'),
    path('upload_xray_pdf/', views.upload_xray_pdf, name='upload_xray_pdf'),
    path('upload_vitals_pdf/', views.upload_vitals_pdf, name='upload_vitals_pdf'),
    path('upload_optometry_pdf/', views.upload_optometry_pdf, name='upload_optometry_pdf'),
    path('upload_audiometry_pdf/', views.upload_audiometry_pdf, name='upload_audiometry_pdf'),
    path('get-csrf-token/', views.get_csrf_token, name='get_csrf_token'),
    path('xray_pdf_report/', views.xray_pdf_report, name='xray_pdf_report'),
    path('client_dashboard/', views.client_dashboard, name='client_dashboard'),
    path('ecg_pdf_report/', views.ecg_pdf_report, name='ecg_pdf_report'),
    path('vitals_pdf_report/', views.vitals_pdf_report, name='vitals_pdf_report'),
    path('optometry_pdf_report/', views.optometry_pdf_report, name='optometry_pdf_report'),
    path('audiometry_pdf_report/', views.audiometry_pdf_report, name='audiometry_pdf_report'),
    path('get_excel/', views.get_excel, name='get_excel'),
    path('googledrive1/', views.GoogleDCM.as_view(), name='get_dcm'),
    path('client/', views.client_dashboard, name='client'),
    path('update_history/', views.update_clinical_history, name='clinical_history'),
    path('optometrylist', views.optometrylist, name='optometrylist'),
    path('vitalslist', views.vitalslist, name='vitalslist'),
    path('api/patient-ids/', views.patient_id_list, name='api_patient_ids'),
    path('delete_all_patients', views.delete_all_patients, name='delete_all_patients'),
    path('delete_all_patients_opto', views.delete_all_patients_opto, name='delete_all_patients_opto'),
    path('add_patient', views.add_patient, name='add_patient'),
    path('add_patient_opto', views.add_patient_opto, name='add_patient_opto'),
    path('add_patient_audio', views.add_patient_audio, name='add_patient_audio'),
    path('delete_all_patients_audio', views.delete_all_patients_audio, name='delete_all_patients_audio'),
    path('reporting_status', views.ReportingStatus, name='reporting_status'),
    path('set_target', views.SetTarget, name='set_target'),
    path('ecg_reporting_status', views.ECGReportingStatus, name='ecg_reporting_status'),
    path('ecg_set_target', views.ECGSetTarget, name='ecg_set_target'),
    path('vaccinationlist', views.vaccinationlist, name='vaccinationlist'),
    path('delete_all_patients_for_vaccination', views.delete_all_patients_for_vaccination, name='delete_all_patients_for_vaccination'),
    path('add_patient_for_vaccination', views.add_patient_for_vaccination, name='add_patient_for_vaccination'),
    path('uploadcsvforvaccination', views.uploadcsvforvaccination, name='uploadcsvforvaccination'),
    path('VaccinationPatientData', views.vaccinationpatientDetails, name='VaccinationPatientData'),
    # Adding all the paths and routes for the ecg and xray automation. - Himanshu.
    path('ecglist', views.ecglist, name='ecglist'),
    path('xraylist', views.xraylist, name='xraylist'),
    path('delete_all_patients_for_ecg', views.delete_all_patients_for_ecg, name='delete_all_patients_for_ecg'),
    path('delete_all_patients_for_xray', views.delete_all_patients_for_xray, name='delete_all_patients_for_xray'),
    path('add_patient_for_ecg', views.add_patient_for_ecg, name='add_patient_for_ecg'),
    path('add_patient_for_xray', views.add_patient_for_xray, name='add_patient_for_xray'),
    path('uploadcsvforecg', views.uploadcsvforecg, name='uploadcsvforecg'),
    path('uploadcsvforxray', views.uploadcsvforxray, name='uploadcsvforxray'),
    path('ecgPatientData', views.ecgpatientDetails, name='ecgPatientData'),
    path('xrayPatientData', views.xraypatientDetails, name='xrayPatientData'),
    # End of ecg and xray routes. - Himanshu.
    path('upload-ecg/', views.upload_ecg, name='upload_ecg'),

    # path('auto_sync/', views.Auto_Sync, name='get_dcm_files'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)