# Generated by Django 5.0.1 on 2024-02-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicomdata',
            name='radiologist',
        ),
        migrations.AddField(
            model_name='dicomdata',
            name='radiologists',
            field=models.ManyToManyField(blank=True, to='users.personalinfo'),
        ),
    ]
