# Generated by Django 5.0.1 on 2024-03-02 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_exportlist_personalinfo_exportlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicomdata',
            name='radiologist',
        ),
        migrations.AddField(
            model_name='dicomdata',
            name='radiologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.personalinfo'),
        ),
    ]
