# Generated by Django 5.0.1 on 2024-03-02 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_dicomdata_radiologist_dicomdata_radiologist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicomdata',
            name='dicom_file',
        ),
        migrations.RemoveField(
            model_name='dicomdata',
            name='jpeg_file',
        ),
        migrations.AddField(
            model_name='dicomdata',
            name='body_part_examined',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DICOMFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dicom_file', models.FileField(upload_to='dicom_files/')),
                ('dicom_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dicom_files', to='users.dicomdata')),
            ],
        ),
        migrations.CreateModel(
            name='JPEGFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jpeg_file', models.ImageField(upload_to='jpeg_files/')),
                ('dicom_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jpeg_files', to='users.dicomdata')),
            ],
        ),
    ]
