# Generated by Django 5.0.1 on 2024-03-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_dicomdata_dicom_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicomdata',
            name='radiologist',
        ),
        migrations.AddField(
            model_name='dicomdata',
            name='radiologist',
            field=models.ManyToManyField(blank=True, to='users.personalinfo'),
        ),
    ]
