# Generated by Django 3.2.25 on 2024-03-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_dicomdata_total_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='reportimage',
            field=models.FileField(default='upload/', upload_to='ecg_graphs/'),
        ),
    ]
