# Generated by Django 3.2.25 on 2024-03-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_patientdetails_reportimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ecg_graphs/'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='reportimage',
            field=models.FileField(blank=True, null=True, upload_to='ecg_graphs/'),
        ),
    ]
