# Generated by Django 5.0.3 on 2024-03-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20240308_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='cardiologist_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
