# Generated by Django 5.0.3 on 2024-03-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_personalinfo_cardiologist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='cardiologist_name',
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='ReportDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='TestDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
