# Generated by Django 5.0.3 on 2024-04-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_xclient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomdata',
            name='NonReportable',
            field=models.BooleanField(default=False),
        ),
    ]
