# Generated by Django 5.0.3 on 2024-04-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_total_cases_total_nonreported_xray'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomdata',
            name='TotalProposalbyClient',
            field=models.IntegerField(default=0),
        ),
    ]
