# Generated by Django 5.0.3 on 2024-04-04 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_dicomdata_totalproposalbyclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomdata',
            name='date_field',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
