# Generated by Django 5.0.3 on 2024-04-04 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_dicomdata_date_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicomdata',
            name='TotalProposalbyClient',
        ),
        migrations.RemoveField(
            model_name='dicomdata',
            name='date_field',
        ),
        migrations.AddField(
            model_name='xclient',
            name='TotalProposalbyClient',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='xclient',
            name='date_field',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
