# Generated by Django 5.0.3 on 2024-04-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_dicomdata_totalproposalbyclient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xclient',
            name='TotalProposalbyClient',
        ),
        migrations.RemoveField(
            model_name='xclient',
            name='date_field',
        ),
    ]
