# Generated by Django 5.0.3 on 2024-04-04 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_xclient_totalproposalbyclient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalProposalbyClient', models.IntegerField(default=0)),
                ('date_field', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
