# Generated by Django 5.0.3 on 2024-04-04 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_setcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='setcount',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.xclient'),
        ),
    ]
