# Generated by Django 5.0.3 on 2024-04-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_setcount_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinfo',
            name='blood',
        ),
        migrations.RemoveField(
            model_name='patientinfo',
            name='height',
        ),
        migrations.RemoveField(
            model_name='patientinfo',
            name='pulse',
        ),
        migrations.RemoveField(
            model_name='patientinfo',
            name='weight',
        ),
    ]
