# Generated by Django 5.0.3 on 2024-04-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_patientinfo_blood_remove_patientinfo_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setcount',
            name='TotalCasesDone',
            field=models.IntegerField(default=0),
        ),
    ]
