# Generated by Django 5.0.3 on 2024-04-06 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_ecgsetcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.location'),
        ),
    ]
