# Generated by Django 5.0.1 on 2024-06-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='AddLeft',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='AddRight',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='AxisLeft',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='AxisRight',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='CylindricalLeft',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='CylindricalRight',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='SphericalLeft',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='SphericalRight',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
