# Generated by Django 5.0.1 on 2024-06-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_patientinfo_addleft_patientinfo_addright_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='vaccinationPatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientId', models.CharField(max_length=50, null=True)),
                ('PatientName', models.CharField(max_length=70, null=True)),
                ('age', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('Hepatitis_E_Batch_No', models.CharField(max_length=50, null=True)),
                ('Hepatitis_E_Manufacturing_Date', models.CharField(max_length=50, null=True)),
                ('Hepatitis_E_Expiry_Date', models.CharField(max_length=50, null=True)),
                ('Typhoid_Batch_No', models.CharField(max_length=50, null=True)),
                ('Typhoid_Manufacturing_Date', models.CharField(max_length=50, null=True)),
                ('Typhoid_Expiry_Date', models.CharField(max_length=50, null=True)),
                ('Date', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
