# Generated by Django 5.0.1 on 2024-06-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_vaccinationpatientdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomdata',
            name='accession_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
