# Generated by Django 5.1 on 2024-10-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_patientdetails_nonreportable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
