# Generated by Django 5.1 on 2024-10-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_patientdetails_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomdata',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
